name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      # see https://blog.utgw.net/entry/2023/06/16/162330
      - run: go install github.com/mfridman/tparse@latest
      - run: go test ./... -json > testresult.out
      - run: tparse -file=testresult.out -format markdown >> $GITHUB_STEP_SUMMARY
