name: ci

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: go install github.com/mfridman/tparse@latest
      - run: go test ./... -cover -json > testresult.out
      - run: tparse -file=testresult.out -format markdown >> $GITHUB_STEP_SUMMARY

  e2e:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: actions/checkout@v4
        with:
          path: build
      - run: go install
        working-directory: build

      - run: mkdir tmp1 tmp2

      - run: touch a.txt
        working-directory: tmp1
      - run: cpbuf c .
        working-directory: tmp1
      - run: cpbuf p
        working-directory: tmp2
      - run: diff tmp1 tmp2
