name: ci

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - run: go install github.com/mfridman/tparse@latest
      - run: go test ./... -cover -json > testresult.out
      - run: tparse -file=testresult.out -format markdown >> $GITHUB_STEP_SUMMARY
